export type ThemeColorTemplate = 
  | 'yellow' | 'red' | 'green' | 'blue' | 'purple'
  | 'amber' | 'terracotta' | 'emerald' | 'sapphire' | 'amethyst' 
  | 'espresso' | 'midnight' | 'monochrome';

export interface ThemeDefinition {
  id: ThemeColorTemplate;
  name: string;
  tagline: string;
  primary: string;
  hover: string;
  light: string;
  text: string;
  border: string;
  buttonText: string;
  btnText: string; // compatibility alias
  title: string;
  bgClass: string;
  cardClass: string;
  cardBorder: string;
  swatchPrimary: string;
  swatchBg: string;
  swatchCard: string;
}

export const THEME_TEMPLATES: ThemeDefinition[] = [
  {
    id: 'amber',
    name: 'Warm Bistro Amber',
    tagline: 'Warm cream canvas, golden amber accents, rich bistro feel',
    primary: 'bg-amber-500',
    hover: 'hover:bg-amber-600',
    light: 'bg-amber-50 dark:bg-amber-950/50',
    text: 'text-amber-700 dark:text-amber-400',
    border: 'border-amber-500',
    buttonText: 'text-zinc-950',
    btnText: 'text-zinc-950',
    title: 'text-amber-700 dark:text-amber-400',
    bgClass: 'bg-[#FBF8F3] dark:bg-[#161412]',
    cardClass: 'bg-white dark:bg-[#221E1A]',
    cardBorder: 'border-amber-200/60 dark:border-stone-800',
    swatchPrimary: '#F59E0B',
    swatchBg: '#FBF8F3',
    swatchCard: '#FFFFFF',
  },
  {
    id: 'terracotta',
    name: 'Tuscan Terracotta',
    tagline: 'Warm sunbaked red clay, rustic Italian trattoria charm',
    primary: 'bg-orange-600',
    hover: 'hover:bg-orange-700',
    light: 'bg-orange-50 dark:bg-orange-950/50',
    text: 'text-orange-600 dark:text-orange-400',
    border: 'border-orange-500',
    buttonText: 'text-white',
    btnText: 'text-white',
    title: 'text-orange-700 dark:text-orange-400',
    bgClass: 'bg-[#FDF6F2] dark:bg-[#1C1412]',
    cardClass: 'bg-white dark:bg-[#251A18]',
    cardBorder: 'border-orange-200/60 dark:border-stone-800',
    swatchPrimary: '#EA580C',
    swatchBg: '#FDF6F2',
    swatchCard: '#FFFFFF',
  },
  {
    id: 'emerald',
    name: 'Matcha Zen Garden',
    tagline: 'Calming botanical green, artisanal tea house aesthetic',
    primary: 'bg-emerald-600',
    hover: 'hover:bg-emerald-700',
    light: 'bg-emerald-50 dark:bg-emerald-950/50',
    text: 'text-emerald-700 dark:text-emerald-400',
    border: 'border-emerald-500',
    buttonText: 'text-white',
    btnText: 'text-white',
    title: 'text-emerald-800 dark:text-emerald-300',
    bgClass: 'bg-[#F4F8F4] dark:bg-[#101913]',
    cardClass: 'bg-white dark:bg-[#18241C]',
    cardBorder: 'border-emerald-100 dark:border-emerald-950/60',
    swatchPrimary: '#059669',
    swatchBg: '#F4F8F4',
    swatchCard: '#FFFFFF',
  },
  {
    id: 'sapphire',
    name: 'Ocean Sapphire',
    tagline: 'Fresh coastal blue, modern seafood & cocktail bar',
    primary: 'bg-sky-600',
    hover: 'hover:bg-sky-700',
    light: 'bg-sky-50 dark:bg-sky-950/50',
    text: 'text-sky-700 dark:text-sky-400',
    border: 'border-sky-500',
    buttonText: 'text-white',
    btnText: 'text-white',
    title: 'text-sky-800 dark:text-sky-300',
    bgClass: 'bg-[#F1F7FB] dark:bg-[#0E1722]',
    cardClass: 'bg-white dark:bg-[#15212E]',
    cardBorder: 'border-sky-100 dark:border-slate-800',
    swatchPrimary: '#0284C7',
    swatchBg: '#F1F7FB',
    swatchCard: '#FFFFFF',
  },
  {
    id: 'amethyst',
    name: 'Velvet Plum & Wine',
    tagline: 'Opulent berry & grape, romantic wine bar & fine dining',
    primary: 'bg-purple-600',
    hover: 'hover:bg-purple-700',
    light: 'bg-purple-50 dark:bg-purple-950/50',
    text: 'text-purple-700 dark:text-purple-400',
    border: 'border-purple-500',
    buttonText: 'text-white',
    btnText: 'text-white',
    title: 'text-purple-800 dark:text-purple-300',
    bgClass: 'bg-[#FAF5F9] dark:bg-[#1B1119]',
    cardClass: 'bg-white dark:bg-[#251823]',
    cardBorder: 'border-purple-100 dark:border-zinc-800',
    swatchPrimary: '#9333EA',
    swatchBg: '#FAF5F9',
    swatchCard: '#FFFFFF',
  },
  {
    id: 'espresso',
    name: 'Artisan Espresso Roast',
    tagline: 'Deep coffee roast, warm toasted oak, specialty roastery',
    primary: 'bg-[#78350F]',
    hover: 'hover:bg-[#92400E]',
    light: 'bg-amber-50 dark:bg-[#28211A]',
    text: 'text-[#92400E] dark:text-[#FCD34D]',
    border: 'border-[#78350F]',
    buttonText: 'text-amber-50',
    btnText: 'text-amber-50',
    title: 'text-[#78350F] dark:text-[#FBBF24]',
    bgClass: 'bg-[#F7F4F0] dark:bg-[#151210]',
    cardClass: 'bg-white dark:bg-[#201B17]',
    cardBorder: 'border-stone-200/80 dark:border-stone-800',
    swatchPrimary: '#78350F',
    swatchBg: '#F7F4F0',
    swatchCard: '#FFFFFF',
  },
  {
    id: 'midnight',
    name: 'Tokyo Midnight Noir',
    tagline: 'Deep noir night, neon amber glow, late-night izakaya vibe',
    primary: 'bg-amber-400',
    hover: 'hover:bg-amber-300',
    light: 'bg-zinc-800 text-amber-300',
    text: 'text-amber-400 dark:text-amber-300',
    border: 'border-amber-400',
    buttonText: 'text-black',
    btnText: 'text-black',
    title: 'text-amber-400 dark:text-amber-300',
    bgClass: 'bg-[#0E0F12] dark:bg-[#090A0D]',
    cardClass: 'bg-[#16181D] dark:bg-[#121317]',
    cardBorder: 'border-zinc-800 dark:border-zinc-800/80',
    swatchPrimary: '#FBBF24',
    swatchBg: '#0E0F12',
    swatchCard: '#16181D',
  },
  {
    id: 'monochrome',
    name: 'Nordic Minimalist',
    tagline: 'High-contrast clean gallery, modern Scandinavian simplicity',
    primary: 'bg-zinc-900 dark:bg-white',
    hover: 'hover:bg-black dark:hover:bg-zinc-200',
    light: 'bg-zinc-100 dark:bg-zinc-800',
    text: 'text-zinc-900 dark:text-white',
    border: 'border-zinc-900 dark:border-white',
    buttonText: 'text-white dark:text-zinc-950',
    btnText: 'text-white dark:text-zinc-950',
    title: 'text-zinc-900 dark:text-white',
    bgClass: 'bg-[#F9FAFB] dark:bg-[#0A0A0C]',
    cardClass: 'bg-white dark:bg-[#18181B]',
    cardBorder: 'border-gray-200/80 dark:border-zinc-800',
    swatchPrimary: '#18181B',
    swatchBg: '#F9FAFB',
    swatchCard: '#FFFFFF',
  },
  {
    id: 'yellow',
    name: 'Classic Sunny Yellow',
    tagline: 'High-energy fast-casual yellow with clean white cards',
    primary: 'bg-yellow-500',
    hover: 'hover:bg-yellow-600',
    light: 'bg-yellow-50 dark:bg-yellow-950/50',
    text: 'text-yellow-600 dark:text-yellow-400',
    border: 'border-yellow-500',
    buttonText: 'text-zinc-950',
    btnText: 'text-zinc-950',
    title: 'text-yellow-700 dark:text-yellow-400',
    bgClass: 'bg-[#FCFAF5] dark:bg-[#151411]',
    cardClass: 'bg-white dark:bg-[#201E1A]',
    cardBorder: 'border-yellow-200/70 dark:border-stone-800',
    swatchPrimary: '#EAB308',
    swatchBg: '#FCFAF5',
    swatchCard: '#FFFFFF',
  },
  {
    id: 'red',
    name: 'Spicy Chili Red',
    tagline: 'Fiery crimson for ramen, hotpot, BBQ, and grills',
    primary: 'bg-red-600',
    hover: 'hover:bg-red-700',
    light: 'bg-red-50 dark:bg-red-950/50',
    text: 'text-red-600 dark:text-red-400',
    border: 'border-red-600',
    buttonText: 'text-white',
    btnText: 'text-white',
    title: 'text-red-700 dark:text-red-400',
    bgClass: 'bg-[#FDF6F6] dark:bg-[#1A1111]',
    cardClass: 'bg-white dark:bg-[#261818]',
    cardBorder: 'border-red-200/70 dark:border-stone-800',
    swatchPrimary: '#EF4444',
    swatchBg: '#FDF6F6',
    swatchCard: '#FFFFFF',
  },
  {
    id: 'green',
    name: 'Fresh Bistro Green',
    tagline: 'Bright botanical green for salad bars and fresh bowls',
    primary: 'bg-green-600',
    hover: 'hover:bg-green-700',
    light: 'bg-green-50 dark:bg-green-950/50',
    text: 'text-green-600 dark:text-green-400',
    border: 'border-green-600',
    buttonText: 'text-white',
    btnText: 'text-white',
    title: 'text-green-700 dark:text-green-400',
    bgClass: 'bg-[#F5FBF6] dark:bg-[#101812]',
    cardClass: 'bg-white dark:bg-[#18261B]',
    cardBorder: 'border-green-200/70 dark:border-stone-800',
    swatchPrimary: '#22C55E',
    swatchBg: '#F5FBF6',
    swatchCard: '#FFFFFF',
  },
  {
    id: 'blue',
    name: 'Cobalt Blue',
    tagline: 'Refreshing oceanic cobalt for seafood and beverage lounges',
    primary: 'bg-blue-600',
    hover: 'hover:bg-blue-700',
    light: 'bg-blue-50 dark:bg-blue-950/50',
    text: 'text-blue-600 dark:text-blue-400',
    border: 'border-blue-600',
    buttonText: 'text-white',
    btnText: 'text-white',
    title: 'text-blue-700 dark:text-blue-400',
    bgClass: 'bg-[#F4F8FD] dark:bg-[#0F1622]',
    cardClass: 'bg-white dark:bg-[#172233]',
    cardBorder: 'border-blue-200/70 dark:border-stone-800',
    swatchPrimary: '#3B82F6',
    swatchBg: '#F4F8FD',
    swatchCard: '#FFFFFF',
  },
  {
    id: 'purple',
    name: 'Deep Violet Purple',
    tagline: 'Modern violet plum for dessert cafes and creative dining',
    primary: 'bg-purple-600',
    hover: 'hover:bg-purple-700',
    light: 'bg-purple-50 dark:bg-purple-950/50',
    text: 'text-purple-600 dark:text-purple-400',
    border: 'border-purple-600',
    buttonText: 'text-white',
    btnText: 'text-white',
    title: 'text-purple-700 dark:text-purple-400',
    bgClass: 'bg-[#FAF6FD] dark:bg-[#17101E]',
    cardClass: 'bg-white dark:bg-[#24192E]',
    cardBorder: 'border-purple-200/70 dark:border-stone-800',
    swatchPrimary: '#A855F7',
    swatchBg: '#FAF6FD',
    swatchCard: '#FFFFFF',
  }
];

export const getThemeClasses = (color: string): ThemeDefinition => {
  const match = THEME_TEMPLATES.find(t => t.id === color);
  return match || THEME_TEMPLATES[0];
};
